"""empty message

Revision ID: 14929728db5b
Revises: ed457526b6f6
Create Date: 2019-11-05 15:15:17.400534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14929728db5b'
down_revision = 'ed457526b6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logger', sa.Column('instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logger', 'instance', ['instance_id'], ['id'])
    op.drop_column('logger', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logger', sa.Column('name', sa.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'logger', type_='foreignkey')
    op.drop_column('logger', 'instance_id')
    # ### end Alembic commands ###
